# Generated by Django 5.2.5 on 2025-09-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ShopByConcern", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(default=None, max_length=150, null=True),
                ),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Skintype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "skintype",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("original_price", models.FloatField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                ("best_seller", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("review_count", models.IntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[("30ml", "30 mL"), ("50ml", "50 mL")],
                        default="30ml",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.category",
                    ),
                ),
                (
                    "shopbyconcern",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="ShopByConcern.shopbyconcern",
                    ),
                ),
                (
                    "similar_products",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="product.product"
                    ),
                ),
                (
                    "skin_types",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="product.skintype"
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/ingredients/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_ingredients",
            },
        ),
        migrations.CreateModel(
            name="HowToUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/how_to_use/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "how_to_use",
            },
        ),
        migrations.CreateModel(
            name="CustomerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer/results/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "customer_result",
            },
        ),
        migrations.CreateModel(
            name="Benefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/benefits/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_benefits",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/images/"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_image",
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer", models.CharField(blank=True, max_length=100, null=True)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "review",
            },
        ),
    ]
