# Generated by Django 5.2.5 on 2025-12-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
