# Generated by Django 5.2.5 on 2025-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0002_skintype_product_best_seller_alter_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
