# Generated by Django 5.2.5 on 2025-08-17 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AlterModelTable(
            name="skintype",
            table="skintype",
        ),
    ]
