# Generated by Django 5.2.5 on 2025-08-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
    ]
