# Generated by Django 5.2.5 on 2025-08-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
