# Generated by Django 5.2.5 on 2025-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_remove_product_reviews_count_remove_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
