# Generated by Django 5.2.5 on 2025-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
