# Generated by Django 5.2.5 on 2025-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_benefits_customerresult_howtouse_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="howtouse",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/how_to_use/"
            ),
        ),
    ]
