# Generated by Django 5.2.5 on 2025-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_howtouse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('consumer_results', 'Consumer Results'), ('benefits', 'Benefits'), ('how_to_use', 'How to Use'), ('ingredients', 'Ingredients'), ('similar_products', 'Similar Products'), ('reviews', 'Product Reviews')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=200, null=True)),
                ('no_data_message', models.CharField(blank=True, default='No data available for this product.', max_length=200, null=True)),
            ],
            options={
                'db_table': 'section_config',
            },
        ),
    ]
