# Generated by Django 5.2.5 on 2025-08-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_sectionconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionConfig',
        ),
    ]
