# Generated by Django 5.2.5 on 2025-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopByConcern", "0001_initial"),
        ("product", "0018_delete_sectionconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shopbyconcern",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="ShopByConcern.shopbyconcern"
            ),
        ),
    ]
