# Generated by Django 5.2.5 on 2025-09-16 05:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_faq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidemodule",
            name="description",
        ),
        migrations.AddField(
            model_name="guidemodule",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
