# Generated by Django 5.2.5 on 2025-09-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_remove_guidemodule_description_guidemodule_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidemodule",
            name="title",
        ),
    ]
