# Generated by Django 5.2.5 on 2025-09-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0004_remove_guidemodule_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidemodule",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
