# Generated by Django 5.2.5 on 2025-11-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizchoice",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vata", "Vata"),
                    ("pitta", "Pitta"),
                    ("kapha", "Kapha"),
                    ("vata-pitta", "Vata-Pitta"),
                    ("vata-kapha", "Vata-Kapha"),
                    ("pitta-kapha", "Pitta-Kapha"),
                ],
                help_text="Select the body type this choice contributes to.",
                max_length=20,
                null=True,
            ),
        ),
    ]
