# Generated by Django 5.2.5 on 2025-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizchoice_body_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerquizlog",
            name="body_type_ratios",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerquizlog",
            name="body_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
