# Generated by Django 5.2.5 on 2025-11-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_customerquizlog_body_type_ratios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerquizlog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizchoice",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizimage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
