# Generated by Django 5.2.5 on 2025-09-14 04:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyureTreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ayuretreat/images/')),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('days_count', models.PositiveIntegerField(default=7, help_text='Number of days for the retreat')),
            ],
            options={
                'db_table': 'ayuretreat',
            },
        ),
        migrations.CreateModel(
            name='RetreatHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ayure_treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='ayuretreat.ayuretreat')),
            ],
            options={
                'db_table': 'retreat_highlights',
            },
        ),
        migrations.CreateModel(
            name='Whoisitfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('ayure_treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_it_for', to='ayuretreat.ayuretreat')),
            ],
            options={
                'db_table': 'who_is_it_for',
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('content', tinymce.models.HTMLField()),
                ('ayure_treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_days', to='ayuretreat.ayuretreat')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('ayure_treat', 'day_number')},
            },
        ),
    ]
