# Generated by Django 5.2.5 on 2025-09-20 16:55

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AyureTreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_start_date", models.DateField(null=True)),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(default=None, max_length=1000, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ayuretreat/images/"
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(default=None, max_length=200, null=True)),
                (
                    "days_count",
                    models.PositiveIntegerField(
                        default=7, help_text="Number of days for the retreat"
                    ),
                ),
            ],
            options={
                "db_table": "ayuretreat",
            },
        ),
        migrations.CreateModel(
            name="BookingInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "reason_for_retreat",
                    models.TextField(
                        help_text="Why the person wants to join the retreat"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ayure_treat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_inquiries",
                        to="ayuretreat.ayuretreat",
                    ),
                ),
            ],
            options={
                "db_table": "booking_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("content", tinymce.models.HTMLField()),
                (
                    "ayure_treat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_days",
                        to="ayuretreat.ayuretreat",
                    ),
                ),
            ],
            options={
                "db_table": "program_days",
            },
        ),
        migrations.CreateModel(
            name="RetreatHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "ayure_treat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="ayuretreat.ayuretreat",
                    ),
                ),
            ],
            options={
                "db_table": "retreat_highlights",
            },
        ),
        migrations.CreateModel(
            name="Whoisitfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ayure_treat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_is_it_for",
                        to="ayuretreat.ayuretreat",
                    ),
                ),
            ],
            options={
                "db_table": "who_is_it_for",
            },
        ),
    ]
