# Generated by Django 5.2.5 on 2025-09-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuretreat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='programday',
            table='program_days',
        ),
    ]
