# Generated by Django 5.2.5 on 2025-11-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayuretreat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayuretreat",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookinginquiry",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programday",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retreathighlight",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoisitfor",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
