# Generated by Django 5.2.5 on 2025-12-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayuretreat", "0002_ayuretreat_is_deleted_bookinginquiry_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinginquiry",
            name="phone_number",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
