# Generated by Django 5.2.5 on 2025-09-14 05:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuretreat', '0002_alter_programday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreathighlight',
            name='description',
        ),
        migrations.RemoveField(
            model_name='retreathighlight',
            name='title',
        ),
        migrations.AddField(
            model_name='retreathighlight',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
