# Generated by Django 5.2.5 on 2025-09-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayuretreat", "0003_remove_retreathighlight_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ayuretreat",
            name="date",
        ),
        migrations.AddField(
            model_name="ayuretreat",
            name="event_start_date",
            field=models.DateField(null=True),
        ),
    ]
