# Generated by Django 5.2.5 on 2025-09-20 16:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50, null=True)),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/images/"),
                ),
                ("tags", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "blog",
            },
        ),
    ]
