# Generated by Django 5.2.5 on 2025-08-17 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="blog",
        ),
    ]
