# Generated by Django 5.2.5 on 2025-08-18 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
    ]
