# Generated by Django 5.2.5 on 2025-09-16 06:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blog_image_delete_blogimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="description",
        ),
        migrations.AddField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
