# Generated by Django 5.2.5 on 2025-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hero", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
